export const GET_COMMON_FEEDS = 'FEEDS/GET_COMMON_FEEDS';
export const GET_USER_FEEDS = 'FEEDS/GET_USER_FEEDS';
export const DELETE_FEED = 'FEEDS/DELETE_FEED';
export const ADD_FEED_TO_USER_FEEDS = 'FEEDS/ADD_FEED_TO_USER_FEEDS';
export const ADD_ARTICLE_TO_FAVORITE_LIST =
	'FEEDS/ADD_ARTICLE_TO_FAVORITE_LIST';
export const DELETE_ARTICLE = 'FEEDS/DELETE_ARTICLE';
export const ADD_NEW_FEED = 'FEEDS/ADD_NEW_FEED';
export const SET_TAB_KEY = 'APP/SET_TAB_KEY';
export const INITIALIZED_SUCCESS = 'APP/INITIALIZED_SUCCESS';
export const SET_SHOW_ALERT = 'APP/SET_SHOW_ALERT';
export const SET_AUTH_USER_DATA = 'LOGIN/SET_AUTH_USER_DATA';
